// products action types
export const ADDPRODUCTTOCART = 'ADDPRODUCTTOCART';
export const REMOVEPRODUCTFROMCART = 'REMOVEPRODUCTFROMCART';
export const INCREASEPRODUCTQUANTITY = 'INCREASEPRODUCTQUANTITY';
export const DECREASEPRODUCTQUANTITY = 'DECREASEPRODUCTQUANTITY';
export const DELETEPRODUCTFROMCART = 'DELETEPRODUCTFROMCART';
export const EMPTYCART = 'EMPTYCART';
